from fastapi import APIRouter
from app.api.v1.routes import auth, clinics, health, users, portal, patients, registration, staff, medical_history, rooms, ai, treatment, stroke, settings, recovery, diagnoses, icd10, audit, schedule, notifications, analytics, telemedicine

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(clinics.router)
api_router.include_router(portal.router)
api_router.include_router(patients.router)
api_router.include_router(registration.router)
api_router.include_router(staff.router)
api_router.include_router(medical_history.router)
api_router.include_router(rooms.router)
api_router.include_router(ai.router)
api_router.include_router(treatment.router)
api_router.include_router(stroke.router)
api_router.include_router(settings.router)
api_router.include_router(recovery.router)
api_router.include_router(diagnoses.router)
api_router.include_router(icd10.router)
api_router.include_router(audit.router)
api_router.include_router(schedule.router)
api_router.include_router(notifications.router)
api_router.include_router(analytics.router)
api_router.include_router(telemedicine.router)
