"""add vital_signs table and portal fields

Revision ID: 2cb38742cde2
Revises: 4e224009301f
Create Date: 2026-04-09 01:17:42.723426

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2cb38742cde2'
down_revision: Union[str, None] = '4e224009301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_signs',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('blood_glucose', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_clinic_id'), 'vital_signs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_vital_signs_patient_id'), 'vital_signs', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'], use_alter=True)
    op.add_column('lab_results', sa.Column('visible_to_patient', sa.Boolean(), nullable=False))
    op.add_column('patient_guardians', sa.Column('can_book_appointments', sa.Boolean(), nullable=False))
    op.add_column('patient_guardians', sa.Column('can_view_billing', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('portal_password_hash', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('last_portal_login', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('patients', 'last_portal_login')
    op.drop_column('patients', 'portal_password_hash')
    op.drop_column('patient_guardians', 'can_view_billing')
    op.drop_column('patient_guardians', 'can_book_appointments')
    op.drop_column('lab_results', 'visible_to_patient')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_vital_signs_patient_id'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_clinic_id'), table_name='vital_signs')
    op.drop_table('vital_signs')
    # ### end Alembic commands ###
