"""add monitoring tables

Revision ID: 3666d9f560a6
Revises: de0a6b78e62f
Create Date: 2026-04-16 09:02:13.933357

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3666d9f560a6'
down_revision: Union[str, None] = 'de0a6b78e62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurse_calls',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CALLED', 'ACCEPTED', 'EN_ROUTE', 'ON_SITE', 'RESOLVED', name='nursecallstatus'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_route_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('on_site_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_calls_clinic_id'), 'nurse_calls', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_nurse_calls_patient_id'), 'nurse_calls', ['patient_id'], unique=False)
    op.create_table('room_cameras',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('camera_type', sa.Enum('OVERVIEW', 'BEDSIDE', 'ENTRANCE', 'OTHER', name='cameratype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position_order', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_cameras_clinic_id'), 'room_cameras', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_room_cameras_room_id'), 'room_cameras', ['room_id'], unique=False)
    op.create_table('sensor_devices',
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('device_type', sa.Enum('HEART_RATE', 'SPO2', 'BODY_TEMPERATURE', 'BLOOD_PRESSURE', 'FALL_DETECTOR', 'ROOM_TEMPERATURE', 'HUMIDITY', 'MOTION', 'DOOR', 'NURSE_CALL', name='devicetype'), nullable=False),
    sa.Column('device_category', sa.Enum('WEARABLE', 'STATIONARY', name='devicecategory'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_devices_clinic_id'), 'sensor_devices', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_sensor_devices_patient_id'), 'sensor_devices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sensor_devices_room_id'), 'sensor_devices', ['room_id'], unique=False)
    op.create_table('monitoring_alerts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('FALL_DETECTED', 'HIGH_HEART_RATE', 'LOW_HEART_RATE', 'LOW_SPO2', 'HIGH_BODY_TEMP', 'LOW_BODY_TEMP', 'HIGH_BP_SYSTOLIC', 'LOW_BP_SYSTOLIC', 'HIGH_BP_DIASTOLIC', 'LOW_BP_DIASTOLIC', 'HIGH_ROOM_TEMP', 'LOW_ROOM_TEMP', 'HIGH_HUMIDITY', 'LOW_HUMIDITY', 'NURSE_CALL', 'DEVICE_OFFLINE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alerts_clinic_id'), 'monitoring_alerts', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_patient_id'), 'monitoring_alerts', ['patient_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_secondary', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_sensor_time', 'sensor_readings', ['sensor_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_readings_sensor_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_monitoring_alerts_patient_id'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_clinic_id'), table_name='monitoring_alerts')
    op.drop_table('monitoring_alerts')
    op.drop_index(op.f('ix_sensor_devices_room_id'), table_name='sensor_devices')
    op.drop_index(op.f('ix_sensor_devices_patient_id'), table_name='sensor_devices')
    op.drop_index(op.f('ix_sensor_devices_clinic_id'), table_name='sensor_devices')
    op.drop_table('sensor_devices')
    op.drop_index(op.f('ix_room_cameras_room_id'), table_name='room_cameras')
    op.drop_index(op.f('ix_room_cameras_clinic_id'), table_name='room_cameras')
    op.drop_table('room_cameras')
    op.drop_index(op.f('ix_nurse_calls_patient_id'), table_name='nurse_calls')
    op.drop_index(op.f('ix_nurse_calls_clinic_id'), table_name='nurse_calls')
    op.drop_table('nurse_calls')
    # ### end Alembic commands ###
