"""add voice_settings to patients

Revision ID: 4bb1a84f5501
Revises: e11f674fd59f
Create Date: 2026-04-16 18:46:16.726341

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4bb1a84f5501'
down_revision: Union[str, None] = 'e11f674fd59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('voice_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'voice_settings')
    # ### end Alembic commands ###
