"""initial schema

Revision ID: 4e224009301f
Revises: 
Create Date: 2026-04-08 23:52:29.624932

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4e224009301f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptionplan'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_clinic_id'), 'departments', ['clinic_id'], unique=False)
    op.create_table('drugs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('form', sa.Enum('TABLET', 'CAPSULE', 'INJECTION', 'SYRUP', 'CREAM', 'DROPS', 'INHALER', 'OTHER', name='drugform'), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('interactions', sa.JSON(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_clinic_id'), 'drugs', ['clinic_id'], unique=False)
    op.create_table('exercises',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('UPPER_LIMB', 'LOWER_LIMB', 'BALANCE', 'GAIT', 'COGNITIVE', name='exercisecategory'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='exercisedifficulty'), nullable=False),
    sa.Column('target_joints', sa.JSON(), nullable=True),
    sa.Column('angle_thresholds', sa.JSON(), nullable=True),
    sa.Column('demo_video_url', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('default_sets', sa.Integer(), nullable=True),
    sa.Column('default_reps', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_clinic_id'), 'exercises', ['clinic_id'], unique=False)
    op.create_table('lab_test_catalog',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_ranges', sa.JSON(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('turnaround_hours', sa.Integer(), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_lab_test_catalog_clinic_id'), 'lab_test_catalog', ['clinic_id'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'MANAGE', name='permissionaction'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_clinic_id'), 'permissions', ['clinic_id'], unique=False)
    op.create_table('procedures',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_consent', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_clinic_id'), 'procedures', ['clinic_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_clinic_id'), 'roles', ['clinic_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_clinic_id'), 'suppliers', ['clinic_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CLINIC_ADMIN', 'DOCTOR', 'NURSE', 'PHARMACIST', 'RECEPTIONIST', 'LAB_TECHNICIAN', 'PATIENT', 'GUARDIAN', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attendance',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clock_in', sa.String(length=50), nullable=True),
    sa.Column('clock_out', sa.String(length=50), nullable=True),
    sa.Column('qr_code', sa.String(length=500), nullable=True),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_clinic_id'), 'attendance', ['clinic_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_clinic_id'), 'audit_logs', ['clinic_id'], unique=False)
    op.create_table('inventory',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_clinic_id'), 'inventory', ['clinic_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PATIENT_ASSIGNED', 'LAB_RESULT_READY', 'MEDICATION_DUE', 'APPOINTMENT_REMINDER', 'LOW_STOCK', 'TREATMENT_UPDATED', 'ABNORMAL_RESULT', 'ALLERGY_ALERT', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_clinic_id'), 'notifications', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('passport_number', sa.String(length=100), nullable=True),
    sa.Column('inn', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodtype'), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('assigned_doctor_id', sa.UUID(), nullable=True),
    sa.Column('assigned_nurse_id', sa.UUID(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('registration_source', sa.Enum('WALK_IN', 'ONLINE', 'REFERRAL', 'EMERGENCY', name='registrationsource'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCHARGED', 'DECEASED', 'TRANSFERRED', name='patientstatus'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patients_inn'), 'patients', ['inn'], unique=False)
    op.create_index(op.f('ix_patients_passport_number'), 'patients', ['passport_number'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('ordered_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', 'CANCELLED', name='purchaseorderstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_clinic_id'), 'purchase_orders', ['clinic_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_clinic_id'), 'role_permissions', ['clinic_id'], unique=False)
    op.create_table('rooms',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('room_type', sa.Enum('CONSULTATION', 'WARD', 'ICU', 'OPERATING', 'LAB', 'PHARMACY', 'RECEPTION', 'OTHER', name='roomtype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_clinic_id'), 'rooms', ['clinic_id'], unique=False)
    op.create_table('shifts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('shift_type', sa.Enum('MORNING', 'AFTERNOON', 'NIGHT', 'ON_CALL', name='shifttype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'ABSENT', name='shiftstatus'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_clinic_id'), 'shifts', ['clinic_id'], unique=False)
    op.create_table('staff_schedules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_available', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_schedules_clinic_id'), 'staff_schedules', ['clinic_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type', sa.Enum('CONSULTATION', 'FOLLOW_UP', 'PROCEDURE', 'TELEMEDICINE', name='appointmenttype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_walk_in', sa.Boolean(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_table('beds',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('bed_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'RESERVED', name='bedstatus'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beds_clinic_id'), 'beds', ['clinic_id'], unique=False)
    op.create_table('face_snapshots',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('CAMERA', 'UPLOAD', 'PASSPORT', name='facesnapshotsource'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_snapshots_clinic_id'), 'face_snapshots', ['clinic_id'], unique=False)
    op.create_table('medical_cards',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_medical_cards_clinic_id'), 'medical_cards', ['clinic_id'], unique=False)
    op.create_table('messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_clinic_id'), 'messages', ['clinic_id'], unique=False)
    op.create_table('patient_guardians',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('guardian_user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_guardians_clinic_id'), 'patient_guardians', ['clinic_id'], unique=False)
    op.create_table('stroke_assessments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assessed_by_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', sa.Enum('NIHSS', 'MRS', 'BARTHEL', 'MMSE', 'BECK_DEPRESSION', 'DYSPHAGIA', name='assessmenttype'), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stroke_assessments_clinic_id'), 'stroke_assessments', ['clinic_id'], unique=False)
    op.create_table('bed_assignments',
    sa.Column('bed_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_assignments_clinic_id'), 'bed_assignments', ['clinic_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('face_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['face_snapshot_id'], ['face_snapshots.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_clinic_id'), 'face_embeddings', ['clinic_id'], unique=False)
    op.create_table('visits',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('medical_card_id', sa.UUID(), nullable=True),
    sa.Column('visit_type', sa.Enum('CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'TELEMEDICINE', 'PROCEDURE', name='visittype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='visitstatus'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('examination_notes', sa.Text(), nullable=True),
    sa.Column('diagnosis_codes', sa.JSON(), nullable=True),
    sa.Column('diagnosis_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_card_id'], ['medical_cards.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_clinic_id'), 'visits', ['clinic_id'], unique=False)
    op.create_table('telemedicine_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='telemedicinesessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('patient_questionnaire', sa.JSON(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_telemedicine_sessions_clinic_id'), 'telemedicine_sessions', ['clinic_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='treatmentplanstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_clinic_id'), 'treatment_plans', ['clinic_id'], unique=False)
    op.create_table('invoices',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'PARTIALLY_PAID', 'CANCELLED', 'OVERDUE', name='invoicestatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('insurance_claim_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurance_claim_status', sa.Enum('NONE', 'SUBMITTED', 'APPROVED', 'REJECTED', name='insuranceclaimstatus'), nullable=False),
    sa.Column('foms_claim_number', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_clinic_id'), 'invoices', ['clinic_id'], unique=False)
    op.create_table('lab_orders',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('ordered_by_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'STAT', name='laborderpriority'), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'SAMPLE_COLLECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='laborderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_by_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test_catalog.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_clinic_id'), 'lab_orders', ['clinic_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISPENSED', 'CANCELLED', 'EXPIRED', name='prescriptionstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_clinic_id'), 'prescriptions', ['clinic_id'], unique=False)
    op.create_table('procedure_orders',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=False),
    sa.Column('ordered_by_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ORDERED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='procedureorderstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consent_signed', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_orders_clinic_id'), 'procedure_orders', ['clinic_id'], unique=False)
    op.create_table('rehab_goals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Enum('MOBILITY', 'SPEECH', 'COGNITION', 'ADL', 'PSYCHOLOGICAL', 'SOCIAL', name='rehabdomain'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('baseline_value', sa.String(length=255), nullable=True),
    sa.Column('target_value', sa.String(length=255), nullable=True),
    sa.Column('current_value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACHIEVED', 'PARTIALLY_ACHIEVED', 'NOT_ACHIEVED', 'REVISED', name='rehabgoalstatus'), nullable=False),
    sa.Column('set_by_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehab_goals_clinic_id'), 'rehab_goals', ['clinic_id'], unique=False)
    op.create_table('treatment_plan_items',
    sa.Column('treatment_plan_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('MEDICATION', 'PROCEDURE', 'LAB_TEST', 'THERAPY', 'EXERCISE', 'DIET', 'MONITORING', name='treatmentitemtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='treatmentitemstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plan_items_clinic_id'), 'treatment_plan_items', ['clinic_id'], unique=False)
    op.create_table('exercise_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('reps_completed', sa.Integer(), nullable=True),
    sa.Column('sets_completed', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_sessions_clinic_id'), 'exercise_sessions', ['clinic_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('CONSULTATION', 'PROCEDURE', 'LAB_TEST', 'MEDICATION', 'ROOM', 'OTHER', name='invoiceitemtype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_clinic_id'), 'invoice_items', ['clinic_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('lab_order_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=255), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PRELIMINARY', 'FINAL', 'AMENDED', name='labresultstatus'), nullable=False),
    sa.Column('resulted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_clinic_id'), 'lab_results', ['clinic_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'INSURANCE', 'BANK_TRANSFER', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_clinic_id'), 'payments', ['clinic_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('route', sa.Enum('ORAL', 'IV', 'IM', 'TOPICAL', 'SUBLINGUAL', 'RECTAL', 'INHALATION', 'OTHER', name='routeofadministration'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_prn', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_clinic_id'), 'prescription_items', ['clinic_id'], unique=False)
    op.create_table('rehab_progress',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['rehab_goals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehab_progress_clinic_id'), 'rehab_progress', ['clinic_id'], unique=False)
    op.create_table('exercise_reps',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('rep_number', sa.Integer(), nullable=False),
    sa.Column('max_angle', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_angle', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('form_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exercise_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_reps_clinic_id'), 'exercise_reps', ['clinic_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_reps_clinic_id'), table_name='exercise_reps')
    op.drop_table('exercise_reps')
    op.drop_index(op.f('ix_rehab_progress_clinic_id'), table_name='rehab_progress')
    op.drop_table('rehab_progress')
    op.drop_index(op.f('ix_prescription_items_clinic_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_payments_clinic_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lab_results_clinic_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_invoice_items_clinic_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_exercise_sessions_clinic_id'), table_name='exercise_sessions')
    op.drop_table('exercise_sessions')
    op.drop_index(op.f('ix_treatment_plan_items_clinic_id'), table_name='treatment_plan_items')
    op.drop_table('treatment_plan_items')
    op.drop_index(op.f('ix_rehab_goals_clinic_id'), table_name='rehab_goals')
    op.drop_table('rehab_goals')
    op.drop_index(op.f('ix_procedure_orders_clinic_id'), table_name='procedure_orders')
    op.drop_table('procedure_orders')
    op.drop_index(op.f('ix_prescriptions_clinic_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_lab_orders_clinic_id'), table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_index(op.f('ix_invoices_clinic_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_treatment_plans_clinic_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_telemedicine_sessions_clinic_id'), table_name='telemedicine_sessions')
    op.drop_table('telemedicine_sessions')
    op.drop_index(op.f('ix_visits_clinic_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_face_embeddings_clinic_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_bed_assignments_clinic_id'), table_name='bed_assignments')
    op.drop_table('bed_assignments')
    op.drop_index(op.f('ix_stroke_assessments_clinic_id'), table_name='stroke_assessments')
    op.drop_table('stroke_assessments')
    op.drop_index(op.f('ix_patient_guardians_clinic_id'), table_name='patient_guardians')
    op.drop_table('patient_guardians')
    op.drop_index(op.f('ix_messages_clinic_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_medical_cards_clinic_id'), table_name='medical_cards')
    op.drop_table('medical_cards')
    op.drop_index(op.f('ix_face_snapshots_clinic_id'), table_name='face_snapshots')
    op.drop_table('face_snapshots')
    op.drop_index(op.f('ix_beds_clinic_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_staff_schedules_clinic_id'), table_name='staff_schedules')
    op.drop_table('staff_schedules')
    op.drop_index(op.f('ix_shifts_clinic_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_rooms_clinic_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_role_permissions_clinic_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_purchase_orders_clinic_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_patients_passport_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_inn'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_clinic_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inventory_clinic_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_audit_logs_clinic_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_clinic_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_clinic_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_clinic_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_procedures_clinic_id'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_permissions_clinic_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_lab_test_catalog_clinic_id'), table_name='lab_test_catalog')
    op.drop_table('lab_test_catalog')
    op.drop_index(op.f('ix_exercises_clinic_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_drugs_clinic_id'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_departments_clinic_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('clinics')
    # ### end Alembic commands ###
