"""add portal ratings family reminders tables

Revision ID: 57b54f5ab033
Revises: 637a2f7cfb34
Create Date: 2026-04-22 09:20:16.808393

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '57b54f5ab033'
down_revision: Union[str, None] = '637a2f7cfb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_links',
    sa.Column('primary_patient_id', sa.UUID(), nullable=False),
    sa.Column('linked_patient_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['linked_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['primary_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_links_clinic_id'), 'family_links', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_family_links_linked_patient_id'), 'family_links', ['linked_patient_id'], unique=False)
    op.create_index(op.f('ix_family_links_primary_patient_id'), 'family_links', ['primary_patient_id'], unique=False)
    op.create_table('medication_reminders',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('times', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_reminders_clinic_id'), 'medication_reminders', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_medication_reminders_patient_id'), 'medication_reminders', ['patient_id'], unique=False)
    op.create_table('doctor_ratings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_ratings_clinic_id'), 'doctor_ratings', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_doctor_id'), 'doctor_ratings', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_patient_id'), 'doctor_ratings', ['patient_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_ratings_patient_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_doctor_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_clinic_id'), table_name='doctor_ratings')
    op.drop_table('doctor_ratings')
    op.drop_index(op.f('ix_medication_reminders_patient_id'), table_name='medication_reminders')
    op.drop_index(op.f('ix_medication_reminders_clinic_id'), table_name='medication_reminders')
    op.drop_table('medication_reminders')
    op.drop_index(op.f('ix_family_links_primary_patient_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_linked_patient_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_clinic_id'), table_name='family_links')
    op.drop_table('family_links')
    # ### end Alembic commands ###
