"""add queue notification_logs document_templates

Revision ID: 637a2f7cfb34
Revises: 4bb1a84f5501
Create Date: 2026-04-22 05:25:00.369569

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '637a2f7cfb34'
down_revision: Union[str, None] = '4bb1a84f5501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PRESCRIPTION', 'DISCHARGE', 'REFERRAL', 'CERTIFICATE', 'CONSENT', 'LAB_ORDER', 'OTHER', name='templatecategory'), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_clinic_id'), 'document_templates', ['clinic_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'TELEGRAM', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_type', sa.String(length=100), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_channel'), 'notification_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_logs_clinic_id'), 'notification_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_table('queue_entries',
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='queuestatus'), nullable=False),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_clinic_id'), 'queue_entries', ['clinic_id'], unique=False)
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_index(op.f('ix_queue_entries_clinic_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_clinic_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_channel'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_document_templates_clinic_id'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
