"""add recovery_goals and recovery_domain_weights tables

Revision ID: 850ee38ac644
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 02:49:37.981409

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '850ee38ac644'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_domain_weights',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('VITALS', 'LABS', 'SCALES', 'EXERCISES', 'TREATMENT', name='recoverydomain'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('set_by_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_domain_weights_clinic_id'), 'recovery_domain_weights', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_recovery_domain_weights_patient_id'), 'recovery_domain_weights', ['patient_id'], unique=False)
    op.create_table('recovery_goals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('VITALS', 'LABS', 'SCALES', 'EXERCISES', 'TREATMENT', name='recoverydomain'), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('set_by_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_goals_clinic_id'), 'recovery_goals', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_recovery_goals_patient_id'), 'recovery_goals', ['patient_id'], unique=False)
    op.alter_column('medical_history_entries', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_history_entries', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_recovery_goals_patient_id'), table_name='recovery_goals')
    op.drop_index(op.f('ix_recovery_goals_clinic_id'), table_name='recovery_goals')
    op.drop_table('recovery_goals')
    op.drop_index(op.f('ix_recovery_domain_weights_patient_id'), table_name='recovery_domain_weights')
    op.drop_index(op.f('ix_recovery_domain_weights_clinic_id'), table_name='recovery_domain_weights')
    op.drop_table('recovery_domain_weights')
    # ### end Alembic commands ###
