"""add fiscal_receipts table

Revision ID: 940557d82d12
Revises: a3f7c9d2e1b4
Create Date: 2026-04-22 04:38:06.682537

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '940557d82d12'
down_revision: Union[str, None] = 'a3f7c9d2e1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PRESCRIPTION', 'DISCHARGE', 'REFERRAL', 'CERTIFICATE', 'CONSENT', 'LAB_ORDER', 'OTHER', name='templatecategory'), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_clinic_id'), 'document_templates', ['clinic_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'TELEGRAM', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_type', sa.String(length=100), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_channel'), 'notification_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_logs_clinic_id'), 'notification_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_type', sa.Enum('BED_OCCUPANCY', 'MEDICATION_CONSUMPTION', 'PATIENT_ADMISSIONS', name='predictiontype'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_clinic_id'), 'predictions', ['clinic_id'], unique=False)
    op.create_table('family_links',
    sa.Column('primary_patient_id', sa.UUID(), nullable=False),
    sa.Column('linked_patient_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['linked_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['primary_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_links_clinic_id'), 'family_links', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_family_links_linked_patient_id'), 'family_links', ['linked_patient_id'], unique=False)
    op.create_index(op.f('ix_family_links_primary_patient_id'), 'family_links', ['primary_patient_id'], unique=False)
    op.create_table('medication_reminders',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('times', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_reminders_clinic_id'), 'medication_reminders', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_medication_reminders_patient_id'), 'medication_reminders', ['patient_id'], unique=False)
    op.create_table('doctor_ratings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_ratings_clinic_id'), 'doctor_ratings', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_doctor_id'), 'doctor_ratings', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_ratings_patient_id'), 'doctor_ratings', ['patient_id'], unique=False)
    op.create_table('queue_entries',
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='queuestatus'), nullable=False),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_clinic_id'), 'queue_entries', ['clinic_id'], unique=False)
    op.create_table('visit_summaries',
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('structured_summary', sa.JSON(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'DRAFT', 'APPROVED', 'REJECTED', name='summarystatus'), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_summaries_clinic_id'), 'visit_summaries', ['clinic_id'], unique=False)
    op.create_table('fiscal_receipts',
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('receipt_number', sa.String(length=255), nullable=True),
    sa.Column('fiscal_sign', sa.String(length=255), nullable=True),
    sa.Column('fiscal_document_number', sa.String(length=255), nullable=True),
    sa.Column('fn_serial', sa.String(length=255), nullable=True),
    sa.Column('receipt_url', sa.String(length=1024), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='fiscalstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_receipts_clinic_id'), 'fiscal_receipts', ['clinic_id'], unique=False)
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_index(op.f('ix_fiscal_receipts_clinic_id'), table_name='fiscal_receipts')
    op.drop_table('fiscal_receipts')
    op.drop_index(op.f('ix_visit_summaries_clinic_id'), table_name='visit_summaries')
    op.drop_table('visit_summaries')
    op.drop_index(op.f('ix_queue_entries_clinic_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_doctor_ratings_patient_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_doctor_id'), table_name='doctor_ratings')
    op.drop_index(op.f('ix_doctor_ratings_clinic_id'), table_name='doctor_ratings')
    op.drop_table('doctor_ratings')
    op.drop_index(op.f('ix_medication_reminders_patient_id'), table_name='medication_reminders')
    op.drop_index(op.f('ix_medication_reminders_clinic_id'), table_name='medication_reminders')
    op.drop_table('medication_reminders')
    op.drop_index(op.f('ix_family_links_primary_patient_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_linked_patient_id'), table_name='family_links')
    op.drop_index(op.f('ix_family_links_clinic_id'), table_name='family_links')
    op.drop_table('family_links')
    op.drop_index(op.f('ix_predictions_clinic_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_clinic_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_channel'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_document_templates_clinic_id'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
