"""add bms tables

Revision ID: e11f674fd59f
Revises: 3666d9f560a6
Create Date: 2026-04-16 17:50:10.321327

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e11f674fd59f'
down_revision: Union[str, None] = '3666d9f560a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bms_buildings',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_buildings_clinic_id'), 'bms_buildings', ['clinic_id'], unique=False)
    op.create_table('bms_floors',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grid_cols', sa.Integer(), nullable=False),
    sa.Column('grid_rows', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['bms_buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_floors_building_id'), 'bms_floors', ['building_id'], unique=False)
    op.create_index(op.f('ix_bms_floors_clinic_id'), 'bms_floors', ['clinic_id'], unique=False)
    op.create_table('bms_zones',
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['bms_floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_zones_clinic_id'), 'bms_zones', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_bms_zones_floor_id'), 'bms_zones', ['floor_id'], unique=False)
    op.create_table('bms_rooms',
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('room_type', sa.Enum('WARD', 'CORRIDOR', 'SERVER', 'TECHNICAL', 'OFFICE', 'OPERATING', 'LAB', 'RECEPTION', 'PHARMACY', 'STORAGE', 'BATHROOM', 'KITCHEN', 'OTHER', name='bmsroomtype'), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('grid_w', sa.Integer(), nullable=False),
    sa.Column('grid_h', sa.Integer(), nullable=False),
    sa.Column('linked_room_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['bms_floors.id'], ),
    sa.ForeignKeyConstraint(['linked_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['bms_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_rooms_clinic_id'), 'bms_rooms', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_bms_rooms_floor_id'), 'bms_rooms', ['floor_id'], unique=False)
    op.create_table('bms_equipment',
    sa.Column('bms_room_id', sa.UUID(), nullable=False),
    sa.Column('equipment_type', sa.Enum('AC', 'HEATER', 'LIGHT', 'VENTILATION', 'DOOR_LOCK', 'ELEVATOR', 'PUMP', 'GENERATOR', 'UPS', 'OTHER', name='equipmenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ON', 'OFF', 'ERROR', 'MAINTENANCE', 'STANDBY', name='equipmentstatus'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_controllable', sa.Boolean(), nullable=False),
    sa.Column('last_status_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bms_room_id'], ['bms_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_equipment_bms_room_id'), 'bms_equipment', ['bms_room_id'], unique=False)
    op.create_index(op.f('ix_bms_equipment_clinic_id'), 'bms_equipment', ['clinic_id'], unique=False)
    op.create_table('bms_sensors',
    sa.Column('bms_room_id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('sensor_type', sa.Enum('TEMPERATURE', 'HUMIDITY', 'CO2', 'LIGHT', 'SMOKE', 'WATER_LEAK', 'MOTION', 'DOOR_SENSOR', 'POWER_METER', 'PIPE_TEMPERATURE', name='bmssensortype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_value_text', sa.String(length=50), nullable=True),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grid_x_offset', sa.Float(), nullable=False),
    sa.Column('grid_y_offset', sa.Float(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bms_room_id'], ['bms_rooms.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['bms_floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_sensors_bms_room_id'), 'bms_sensors', ['bms_room_id'], unique=False)
    op.create_index(op.f('ix_bms_sensors_clinic_id'), 'bms_sensors', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_bms_sensors_floor_id'), 'bms_sensors', ['floor_id'], unique=False)
    op.create_table('bms_alerts',
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.Column('bms_room_id', sa.UUID(), nullable=True),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('HIGH_TEMPERATURE', 'LOW_TEMPERATURE', 'HIGH_HUMIDITY', 'LOW_HUMIDITY', 'HIGH_CO2', 'SMOKE_DETECTED', 'WATER_LEAK', 'POWER_OUTAGE', 'EQUIPMENT_ERROR', 'DOOR_FORCED', 'MOTION_AFTER_HOURS', 'SENSOR_OFFLINE', 'PIPE_FREEZE_RISK', name='bmsalerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', 'EMERGENCY', name='bmsalertseverity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'AUTO_RESOLVED', name='bmsalertstatus'), nullable=False),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bms_room_id'], ['bms_rooms.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['bms_equipment.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['bms_floors.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['bms_sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_alerts_clinic_id'), 'bms_alerts', ['clinic_id'], unique=False)
    op.create_table('bms_automation_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('condition_sensor_type', sa.String(length=50), nullable=False),
    sa.Column('condition_operator', sa.Enum('GT', 'LT', 'EQ', 'GTE', 'LTE', name='conditionoperator'), nullable=False),
    sa.Column('condition_value', sa.Float(), nullable=False),
    sa.Column('condition_floor_id', sa.UUID(), nullable=True),
    sa.Column('condition_room_id', sa.UUID(), nullable=True),
    sa.Column('action_equipment_type', sa.String(length=50), nullable=True),
    sa.Column('action_equipment_id', sa.UUID(), nullable=True),
    sa.Column('action_command', sa.String(length=50), nullable=False),
    sa.Column('action_parameters', sa.JSON(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('schedule_description', sa.String(length=255), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['action_equipment_id'], ['bms_equipment.id'], ),
    sa.ForeignKeyConstraint(['condition_floor_id'], ['bms_floors.id'], ),
    sa.ForeignKeyConstraint(['condition_room_id'], ['bms_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_automation_rules_clinic_id'), 'bms_automation_rules', ['clinic_id'], unique=False)
    op.create_table('bms_equipment_commands',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('command', sa.Enum('TURN_ON', 'TURN_OFF', 'SET_PARAMETER', 'RESTART', name='equipmentcommandtype'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('issued_by_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'FAILED', name='commandstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['bms_equipment.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bms_equipment_commands_clinic_id'), 'bms_equipment_commands', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_bms_equipment_commands_equipment_id'), 'bms_equipment_commands', ['equipment_id'], unique=False)
    op.create_table('bms_sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['bms_sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bms_sensor_readings_sensor_time', 'bms_sensor_readings', ['sensor_id', 'recorded_at'], unique=False)
    op.create_table('bms_automation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.Column('action_taken', sa.String(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['bms_automation_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bms_automation_logs')
    op.drop_index('ix_bms_sensor_readings_sensor_time', table_name='bms_sensor_readings')
    op.drop_table('bms_sensor_readings')
    op.drop_index(op.f('ix_bms_equipment_commands_equipment_id'), table_name='bms_equipment_commands')
    op.drop_index(op.f('ix_bms_equipment_commands_clinic_id'), table_name='bms_equipment_commands')
    op.drop_table('bms_equipment_commands')
    op.drop_index(op.f('ix_bms_automation_rules_clinic_id'), table_name='bms_automation_rules')
    op.drop_table('bms_automation_rules')
    op.drop_index(op.f('ix_bms_alerts_clinic_id'), table_name='bms_alerts')
    op.drop_table('bms_alerts')
    op.drop_index(op.f('ix_bms_sensors_floor_id'), table_name='bms_sensors')
    op.drop_index(op.f('ix_bms_sensors_clinic_id'), table_name='bms_sensors')
    op.drop_index(op.f('ix_bms_sensors_bms_room_id'), table_name='bms_sensors')
    op.drop_table('bms_sensors')
    op.drop_index(op.f('ix_bms_equipment_clinic_id'), table_name='bms_equipment')
    op.drop_index(op.f('ix_bms_equipment_bms_room_id'), table_name='bms_equipment')
    op.drop_table('bms_equipment')
    op.drop_index(op.f('ix_bms_rooms_floor_id'), table_name='bms_rooms')
    op.drop_index(op.f('ix_bms_rooms_clinic_id'), table_name='bms_rooms')
    op.drop_table('bms_rooms')
    op.drop_index(op.f('ix_bms_zones_floor_id'), table_name='bms_zones')
    op.drop_index(op.f('ix_bms_zones_clinic_id'), table_name='bms_zones')
    op.drop_table('bms_zones')
    op.drop_index(op.f('ix_bms_floors_clinic_id'), table_name='bms_floors')
    op.drop_index(op.f('ix_bms_floors_building_id'), table_name='bms_floors')
    op.drop_table('bms_floors')
    op.drop_index(op.f('ix_bms_buildings_clinic_id'), table_name='bms_buildings')
    op.drop_table('bms_buildings')
    # ### end Alembic commands ###
