"""add loyalty_accounts and points_transactions tables

Revision ID: f619606393be
Revises: 940557d82d12
Create Date: 2026-04-22 04:57:49.417974

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f619606393be'
down_revision: Union[str, None] = '940557d82d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_signatures',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_title', sa.String(length=300), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_role', sa.String(length=50), nullable=False),
    sa.Column('signature_hash', sa.String(length=500), nullable=True),
    sa.Column('pin_code_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'REJECTED', 'EXPIRED', name='signaturestatus'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_signatures_clinic_id'), 'document_signatures', ['clinic_id'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_loyalty_accounts_clinic_id'), 'loyalty_accounts', ['clinic_id'], unique=False)
    op.create_table('points_transactions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EARNED', 'SPENT', 'BONUS', 'EXPIRED', name='pointstransactiontype'), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_transactions_clinic_id'), 'points_transactions', ['clinic_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_transactions_clinic_id'), table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_index(op.f('ix_loyalty_accounts_clinic_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index(op.f('ix_document_signatures_clinic_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    # ### end Alembic commands ###
