/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalPortalRouteImport } from './routes/portal/_portal'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PortalPortalResultsRouteImport } from './routes/portal/_portal/results'
import { Route as PortalPortalMessagesRouteImport } from './routes/portal/_portal/messages'
import { Route as PortalPortalMedicalCardRouteImport } from './routes/portal/_portal/medical-card'
import { Route as PortalPortalExercisesRouteImport } from './routes/portal/_portal/exercises'
import { Route as PortalPortalDashboardRouteImport } from './routes/portal/_portal/dashboard'
import { Route as PortalPortalBillingRouteImport } from './routes/portal/_portal/billing'
import { Route as PortalPortalAppointmentsRouteImport } from './routes/portal/_portal/appointments'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients.new'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal/_portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalPortalResultsRoute = PortalPortalResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalMessagesRoute = PortalPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalMedicalCardRoute = PortalPortalMedicalCardRouteImport.update({
  id: '/medical-card',
  path: '/medical-card',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalExercisesRoute = PortalPortalExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalDashboardRoute = PortalPortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalBillingRoute = PortalPortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalAppointmentsRoute =
  PortalPortalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/portal': typeof PortalPortalRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/billing': typeof PortalPortalBillingRoute
  '/portal/dashboard': typeof PortalPortalDashboardRoute
  '/portal/exercises': typeof PortalPortalExercisesRoute
  '/portal/medical-card': typeof PortalPortalMedicalCardRoute
  '/portal/messages': typeof PortalPortalMessagesRoute
  '/portal/results': typeof PortalPortalResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/portal': typeof PortalPortalRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/billing': typeof PortalPortalBillingRoute
  '/portal/dashboard': typeof PortalPortalDashboardRoute
  '/portal/exercises': typeof PortalPortalExercisesRoute
  '/portal/medical-card': typeof PortalPortalMedicalCardRoute
  '/portal/messages': typeof PortalPortalMessagesRoute
  '/portal/results': typeof PortalPortalResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/portal/_portal': typeof PortalPortalRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/portal/_portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/_portal/billing': typeof PortalPortalBillingRoute
  '/portal/_portal/dashboard': typeof PortalPortalDashboardRoute
  '/portal/_portal/exercises': typeof PortalPortalExercisesRoute
  '/portal/_portal/medical-card': typeof PortalPortalMedicalCardRoute
  '/portal/_portal/messages': typeof PortalPortalMessagesRoute
  '/portal/_portal/results': typeof PortalPortalResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients'
    | '/portal'
    | '/portal/login'
    | '/patients/$patientId'
    | '/patients/new'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/dashboard'
    | '/portal/exercises'
    | '/portal/medical-card'
    | '/portal/messages'
    | '/portal/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients'
    | '/portal'
    | '/portal/login'
    | '/patients/$patientId'
    | '/patients/new'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/dashboard'
    | '/portal/exercises'
    | '/portal/medical-card'
    | '/portal/messages'
    | '/portal/results'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/patients'
    | '/portal/_portal'
    | '/portal/login'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/new'
    | '/portal/_portal/appointments'
    | '/portal/_portal/billing'
    | '/portal/_portal/dashboard'
    | '/portal/_portal/exercises'
    | '/portal/_portal/medical-card'
    | '/portal/_portal/messages'
    | '/portal/_portal/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalPortalRoute: typeof PortalPortalRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/_portal': {
      id: '/portal/_portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/_portal/results': {
      id: '/portal/_portal/results'
      path: '/results'
      fullPath: '/portal/results'
      preLoaderRoute: typeof PortalPortalResultsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/messages': {
      id: '/portal/_portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalPortalMessagesRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/medical-card': {
      id: '/portal/_portal/medical-card'
      path: '/medical-card'
      fullPath: '/portal/medical-card'
      preLoaderRoute: typeof PortalPortalMedicalCardRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/exercises': {
      id: '/portal/_portal/exercises'
      path: '/exercises'
      fullPath: '/portal/exercises'
      preLoaderRoute: typeof PortalPortalExercisesRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/dashboard': {
      id: '/portal/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalPortalDashboardRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/billing': {
      id: '/portal/_portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalPortalBillingRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/appointments': {
      id: '/portal/_portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalPortalAppointmentsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
  }
}

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalPortalRouteChildren {
  PortalPortalAppointmentsRoute: typeof PortalPortalAppointmentsRoute
  PortalPortalBillingRoute: typeof PortalPortalBillingRoute
  PortalPortalDashboardRoute: typeof PortalPortalDashboardRoute
  PortalPortalExercisesRoute: typeof PortalPortalExercisesRoute
  PortalPortalMedicalCardRoute: typeof PortalPortalMedicalCardRoute
  PortalPortalMessagesRoute: typeof PortalPortalMessagesRoute
  PortalPortalResultsRoute: typeof PortalPortalResultsRoute
}

const PortalPortalRouteChildren: PortalPortalRouteChildren = {
  PortalPortalAppointmentsRoute: PortalPortalAppointmentsRoute,
  PortalPortalBillingRoute: PortalPortalBillingRoute,
  PortalPortalDashboardRoute: PortalPortalDashboardRoute,
  PortalPortalExercisesRoute: PortalPortalExercisesRoute,
  PortalPortalMedicalCardRoute: PortalPortalMedicalCardRoute,
  PortalPortalMessagesRoute: PortalPortalMessagesRoute,
  PortalPortalResultsRoute: PortalPortalResultsRoute,
}

const PortalPortalRouteWithChildren = PortalPortalRoute._addFileChildren(
  PortalPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalPortalRoute: PortalPortalRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
