/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as BedsideRouteImport } from './routes/bedside'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalPortalRouteImport } from './routes/portal/_portal'
import { Route as AuthenticatedWristbandsRouteImport } from './routes/_authenticated/wristbands'
import { Route as AuthenticatedVisitSummariesRouteImport } from './routes/_authenticated/visit-summaries'
import { Route as AuthenticatedTelemedicineRouteImport } from './routes/_authenticated/telemedicine'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSurgeryRouteImport } from './routes/_authenticated/surgery'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedScheduleCalendarRouteImport } from './routes/_authenticated/schedule-calendar'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedRbacUserRouteImport } from './routes/_authenticated/rbac-user'
import { Route as AuthenticatedRbacRouteImport } from './routes/_authenticated/rbac'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedQrScanRouteImport } from './routes/_authenticated/qr-scan'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedNurseDiaryRouteImport } from './routes/_authenticated/nurse-diary'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotificationLogsRouteImport } from './routes/_authenticated/notification-logs'
import { Route as AuthenticatedMedicineSettingsRouteImport } from './routes/_authenticated/medicine-settings'
import { Route as AuthenticatedLaboratoryRouteImport } from './routes/_authenticated/laboratory'
import { Route as AuthenticatedInfrastructureRouteImport } from './routes/_authenticated/infrastructure'
import { Route as AuthenticatedInfectionControlRouteImport } from './routes/_authenticated/infection-control'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDocumentTemplatesRouteImport } from './routes/_authenticated/document-templates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChiefDashboardRouteImport } from './routes/_authenticated/chief-dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedInfrastructureIndexRouteImport } from './routes/_authenticated/infrastructure/index'
import { Route as PortalPortalTreatmentRouteImport } from './routes/portal/_portal/treatment'
import { Route as PortalPortalScheduleRouteImport } from './routes/portal/_portal/schedule'
import { Route as PortalPortalResultsRouteImport } from './routes/portal/_portal/results'
import { Route as PortalPortalRemindersRouteImport } from './routes/portal/_portal/reminders'
import { Route as PortalPortalRecoveryRouteImport } from './routes/portal/_portal/recovery'
import { Route as PortalPortalRatingsRouteImport } from './routes/portal/_portal/ratings'
import { Route as PortalPortalProfileRouteImport } from './routes/portal/_portal/profile'
import { Route as PortalPortalMessagesRouteImport } from './routes/portal/_portal/messages'
import { Route as PortalPortalMedicalCardRouteImport } from './routes/portal/_portal/medical-card'
import { Route as PortalPortalLoyaltyRouteImport } from './routes/portal/_portal/loyalty'
import { Route as PortalPortalHistoryRouteImport } from './routes/portal/_portal/history'
import { Route as PortalPortalFamilyRouteImport } from './routes/portal/_portal/family'
import { Route as PortalPortalExercisesRouteImport } from './routes/portal/_portal/exercises'
import { Route as PortalPortalExerciseSessionRouteImport } from './routes/portal/_portal/exercise-session'
import { Route as PortalPortalExerciseProgressRouteImport } from './routes/portal/_portal/exercise-progress'
import { Route as PortalPortalDashboardRouteImport } from './routes/portal/_portal/dashboard'
import { Route as PortalPortalClinicInfoRouteImport } from './routes/portal/_portal/clinic-info'
import { Route as PortalPortalBillingRouteImport } from './routes/portal/_portal/billing'
import { Route as PortalPortalAppointmentsRouteImport } from './routes/portal/_portal/appointments'
import { Route as PortalPortalAiChatRouteImport } from './routes/portal/_portal/ai-chat'
import { Route as AuthenticatedStaffNewRouteImport } from './routes/_authenticated/staff.new'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff.$staffId'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients.new'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedInfrastructureSettingsRouteImport } from './routes/_authenticated/infrastructure/settings'
import { Route as AuthenticatedInfrastructureMapRouteImport } from './routes/_authenticated/infrastructure/map'
import { Route as AuthenticatedInfrastructureEquipmentRouteImport } from './routes/_authenticated/infrastructure/equipment'
import { Route as AuthenticatedInfrastructureDashboardRouteImport } from './routes/_authenticated/infrastructure/dashboard'
import { Route as AuthenticatedInfrastructureAutomationRouteImport } from './routes/_authenticated/infrastructure/automation'
import { Route as AuthenticatedPatientsPatientIdIndexRouteImport } from './routes/_authenticated/patients.$patientId/index'
import { Route as AuthenticatedPatientsPatientIdTreatmentRouteImport } from './routes/_authenticated/patients.$patientId/treatment'
import { Route as AuthenticatedPatientsPatientIdStrokeRouteImport } from './routes/_authenticated/patients.$patientId/stroke'
import { Route as AuthenticatedPatientsPatientIdRoomsRouteImport } from './routes/_authenticated/patients.$patientId/rooms'
import { Route as AuthenticatedPatientsPatientIdProceduresRouteImport } from './routes/_authenticated/patients.$patientId/procedures'
import { Route as AuthenticatedPatientsPatientIdOverviewRouteImport } from './routes/_authenticated/patients.$patientId/overview'
import { Route as AuthenticatedPatientsPatientIdMonitoringRouteImport } from './routes/_authenticated/patients.$patientId/monitoring'
import { Route as AuthenticatedPatientsPatientIdMedicationsRouteImport } from './routes/_authenticated/patients.$patientId/medications'
import { Route as AuthenticatedPatientsPatientIdLabsRouteImport } from './routes/_authenticated/patients.$patientId/labs'
import { Route as AuthenticatedPatientsPatientIdHistoryRouteImport } from './routes/_authenticated/patients.$patientId/history'
import { Route as AuthenticatedPatientsPatientIdDynamicsRouteImport } from './routes/_authenticated/patients.$patientId/dynamics'
import { Route as AuthenticatedPatientsPatientIdDocumentsRouteImport } from './routes/_authenticated/patients.$patientId/documents'
import { Route as AuthenticatedPatientsPatientIdDiagnosesRouteImport } from './routes/_authenticated/patients.$patientId/diagnoses'
import { Route as AuthenticatedPatientsPatientIdBillingRouteImport } from './routes/_authenticated/patients.$patientId/billing'
import { Route as AuthenticatedPatientsPatientIdAiRouteImport } from './routes/_authenticated/patients.$patientId/ai'
import { Route as AuthenticatedPatientsPatientIdHistoryIndexRouteImport } from './routes/_authenticated/patients.$patientId/history/index'
import { Route as AuthenticatedPatientsPatientIdHistoryNewRouteImport } from './routes/_authenticated/patients.$patientId/history/new'
import { Route as AuthenticatedPatientsPatientIdHistoryEntryIdRouteImport } from './routes/_authenticated/patients.$patientId/history/$entryId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsideRoute = BedsideRouteImport.update({
  id: '/bedside',
  path: '/bedside',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal/_portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWristbandsRoute = AuthenticatedWristbandsRouteImport.update({
  id: '/wristbands',
  path: '/wristbands',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitSummariesRoute =
  AuthenticatedVisitSummariesRouteImport.update({
    id: '/visit-summaries',
    path: '/visit-summaries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTelemedicineRoute =
  AuthenticatedTelemedicineRouteImport.update({
    id: '/telemedicine',
    path: '/telemedicine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSurgeryRoute = AuthenticatedSurgeryRouteImport.update({
  id: '/surgery',
  path: '/surgery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleCalendarRoute =
  AuthenticatedScheduleCalendarRouteImport.update({
    id: '/schedule-calendar',
    path: '/schedule-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRbacUserRoute = AuthenticatedRbacUserRouteImport.update({
  id: '/rbac-user',
  path: '/rbac-user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRbacRoute = AuthenticatedRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQrScanRoute = AuthenticatedQrScanRouteImport.update({
  id: '/qr-scan',
  path: '/qr-scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNurseDiaryRoute = AuthenticatedNurseDiaryRouteImport.update({
  id: '/nurse-diary',
  path: '/nurse-diary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationLogsRoute =
  AuthenticatedNotificationLogsRouteImport.update({
    id: '/notification-logs',
    path: '/notification-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMedicineSettingsRoute =
  AuthenticatedMedicineSettingsRouteImport.update({
    id: '/medicine-settings',
    path: '/medicine-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLaboratoryRoute = AuthenticatedLaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInfrastructureRoute =
  AuthenticatedInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInfectionControlRoute =
  AuthenticatedInfectionControlRouteImport.update({
    id: '/infection-control',
    path: '/infection-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentTemplatesRoute =
  AuthenticatedDocumentTemplatesRouteImport.update({
    id: '/document-templates',
    path: '/document-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChiefDashboardRoute =
  AuthenticatedChiefDashboardRouteImport.update({
    id: '/chief-dashboard',
    path: '/chief-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedInfrastructureIndexRoute =
  AuthenticatedInfrastructureIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInfrastructureRoute,
  } as any)
const PortalPortalTreatmentRoute = PortalPortalTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalScheduleRoute = PortalPortalScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalResultsRoute = PortalPortalResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalRemindersRoute = PortalPortalRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalRecoveryRoute = PortalPortalRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalRatingsRoute = PortalPortalRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalProfileRoute = PortalPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalMessagesRoute = PortalPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalMedicalCardRoute = PortalPortalMedicalCardRouteImport.update({
  id: '/medical-card',
  path: '/medical-card',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalLoyaltyRoute = PortalPortalLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalHistoryRoute = PortalPortalHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalFamilyRoute = PortalPortalFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalExercisesRoute = PortalPortalExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalExerciseSessionRoute =
  PortalPortalExerciseSessionRouteImport.update({
    id: '/exercise-session',
    path: '/exercise-session',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const PortalPortalExerciseProgressRoute =
  PortalPortalExerciseProgressRouteImport.update({
    id: '/exercise-progress',
    path: '/exercise-progress',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const PortalPortalDashboardRoute = PortalPortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalClinicInfoRoute = PortalPortalClinicInfoRouteImport.update({
  id: '/clinic-info',
  path: '/clinic-info',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalBillingRoute = PortalPortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalAppointmentsRoute =
  PortalPortalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const PortalPortalAiChatRoute = PortalPortalAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => PortalPortalRoute,
} as any)
const AuthenticatedStaffNewRoute = AuthenticatedStaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedInfrastructureSettingsRoute =
  AuthenticatedInfrastructureSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedInfrastructureRoute,
  } as any)
const AuthenticatedInfrastructureMapRoute =
  AuthenticatedInfrastructureMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedInfrastructureRoute,
  } as any)
const AuthenticatedInfrastructureEquipmentRoute =
  AuthenticatedInfrastructureEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedInfrastructureRoute,
  } as any)
const AuthenticatedInfrastructureDashboardRoute =
  AuthenticatedInfrastructureDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedInfrastructureRoute,
  } as any)
const AuthenticatedInfrastructureAutomationRoute =
  AuthenticatedInfrastructureAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => AuthenticatedInfrastructureRoute,
  } as any)
const AuthenticatedPatientsPatientIdIndexRoute =
  AuthenticatedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdTreatmentRoute =
  AuthenticatedPatientsPatientIdTreatmentRouteImport.update({
    id: '/treatment',
    path: '/treatment',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdStrokeRoute =
  AuthenticatedPatientsPatientIdStrokeRouteImport.update({
    id: '/stroke',
    path: '/stroke',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoomsRoute =
  AuthenticatedPatientsPatientIdRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdProceduresRoute =
  AuthenticatedPatientsPatientIdProceduresRouteImport.update({
    id: '/procedures',
    path: '/procedures',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdOverviewRoute =
  AuthenticatedPatientsPatientIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdMonitoringRoute =
  AuthenticatedPatientsPatientIdMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdMedicationsRoute =
  AuthenticatedPatientsPatientIdMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdLabsRoute =
  AuthenticatedPatientsPatientIdLabsRouteImport.update({
    id: '/labs',
    path: '/labs',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdHistoryRoute =
  AuthenticatedPatientsPatientIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdDynamicsRoute =
  AuthenticatedPatientsPatientIdDynamicsRouteImport.update({
    id: '/dynamics',
    path: '/dynamics',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdDocumentsRoute =
  AuthenticatedPatientsPatientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdDiagnosesRoute =
  AuthenticatedPatientsPatientIdDiagnosesRouteImport.update({
    id: '/diagnoses',
    path: '/diagnoses',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdBillingRoute =
  AuthenticatedPatientsPatientIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdAiRoute =
  AuthenticatedPatientsPatientIdAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdHistoryIndexRoute =
  AuthenticatedPatientsPatientIdHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsPatientIdHistoryRoute,
  } as any)
const AuthenticatedPatientsPatientIdHistoryNewRoute =
  AuthenticatedPatientsPatientIdHistoryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPatientsPatientIdHistoryRoute,
  } as any)
const AuthenticatedPatientsPatientIdHistoryEntryIdRoute =
  AuthenticatedPatientsPatientIdHistoryEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => AuthenticatedPatientsPatientIdHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bedside': typeof BedsideRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/chief-dashboard': typeof AuthenticatedChiefDashboardRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/document-templates': typeof AuthenticatedDocumentTemplatesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/infection-control': typeof AuthenticatedInfectionControlRoute
  '/infrastructure': typeof AuthenticatedInfrastructureRouteWithChildren
  '/laboratory': typeof AuthenticatedLaboratoryRoute
  '/medicine-settings': typeof AuthenticatedMedicineSettingsRoute
  '/notification-logs': typeof AuthenticatedNotificationLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/nurse-diary': typeof AuthenticatedNurseDiaryRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/qr-scan': typeof AuthenticatedQrScanRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/rbac-user': typeof AuthenticatedRbacUserRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/schedule-calendar': typeof AuthenticatedScheduleCalendarRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/surgery': typeof AuthenticatedSurgeryRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/visit-summaries': typeof AuthenticatedVisitSummariesRoute
  '/wristbands': typeof AuthenticatedWristbandsRoute
  '/portal': typeof PortalPortalRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/infrastructure/automation': typeof AuthenticatedInfrastructureAutomationRoute
  '/infrastructure/dashboard': typeof AuthenticatedInfrastructureDashboardRoute
  '/infrastructure/equipment': typeof AuthenticatedInfrastructureEquipmentRoute
  '/infrastructure/map': typeof AuthenticatedInfrastructureMapRoute
  '/infrastructure/settings': typeof AuthenticatedInfrastructureSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/staff/new': typeof AuthenticatedStaffNewRoute
  '/portal/ai-chat': typeof PortalPortalAiChatRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/billing': typeof PortalPortalBillingRoute
  '/portal/clinic-info': typeof PortalPortalClinicInfoRoute
  '/portal/dashboard': typeof PortalPortalDashboardRoute
  '/portal/exercise-progress': typeof PortalPortalExerciseProgressRoute
  '/portal/exercise-session': typeof PortalPortalExerciseSessionRoute
  '/portal/exercises': typeof PortalPortalExercisesRoute
  '/portal/family': typeof PortalPortalFamilyRoute
  '/portal/history': typeof PortalPortalHistoryRoute
  '/portal/loyalty': typeof PortalPortalLoyaltyRoute
  '/portal/medical-card': typeof PortalPortalMedicalCardRoute
  '/portal/messages': typeof PortalPortalMessagesRoute
  '/portal/profile': typeof PortalPortalProfileRoute
  '/portal/ratings': typeof PortalPortalRatingsRoute
  '/portal/recovery': typeof PortalPortalRecoveryRoute
  '/portal/reminders': typeof PortalPortalRemindersRoute
  '/portal/results': typeof PortalPortalResultsRoute
  '/portal/schedule': typeof PortalPortalScheduleRoute
  '/portal/treatment': typeof PortalPortalTreatmentRoute
  '/infrastructure/': typeof AuthenticatedInfrastructureIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/patients/$patientId/ai': typeof AuthenticatedPatientsPatientIdAiRoute
  '/patients/$patientId/billing': typeof AuthenticatedPatientsPatientIdBillingRoute
  '/patients/$patientId/diagnoses': typeof AuthenticatedPatientsPatientIdDiagnosesRoute
  '/patients/$patientId/documents': typeof AuthenticatedPatientsPatientIdDocumentsRoute
  '/patients/$patientId/dynamics': typeof AuthenticatedPatientsPatientIdDynamicsRoute
  '/patients/$patientId/history': typeof AuthenticatedPatientsPatientIdHistoryRouteWithChildren
  '/patients/$patientId/labs': typeof AuthenticatedPatientsPatientIdLabsRoute
  '/patients/$patientId/medications': typeof AuthenticatedPatientsPatientIdMedicationsRoute
  '/patients/$patientId/monitoring': typeof AuthenticatedPatientsPatientIdMonitoringRoute
  '/patients/$patientId/overview': typeof AuthenticatedPatientsPatientIdOverviewRoute
  '/patients/$patientId/procedures': typeof AuthenticatedPatientsPatientIdProceduresRoute
  '/patients/$patientId/rooms': typeof AuthenticatedPatientsPatientIdRoomsRoute
  '/patients/$patientId/stroke': typeof AuthenticatedPatientsPatientIdStrokeRoute
  '/patients/$patientId/treatment': typeof AuthenticatedPatientsPatientIdTreatmentRoute
  '/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
  '/patients/$patientId/history/$entryId': typeof AuthenticatedPatientsPatientIdHistoryEntryIdRoute
  '/patients/$patientId/history/new': typeof AuthenticatedPatientsPatientIdHistoryNewRoute
  '/patients/$patientId/history/': typeof AuthenticatedPatientsPatientIdHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bedside': typeof BedsideRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/chat': typeof AuthenticatedChatRoute
  '/chief-dashboard': typeof AuthenticatedChiefDashboardRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/document-templates': typeof AuthenticatedDocumentTemplatesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/infection-control': typeof AuthenticatedInfectionControlRoute
  '/laboratory': typeof AuthenticatedLaboratoryRoute
  '/medicine-settings': typeof AuthenticatedMedicineSettingsRoute
  '/notification-logs': typeof AuthenticatedNotificationLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/nurse-diary': typeof AuthenticatedNurseDiaryRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/qr-scan': typeof AuthenticatedQrScanRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/rbac-user': typeof AuthenticatedRbacUserRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/schedule-calendar': typeof AuthenticatedScheduleCalendarRoute
  '/surgery': typeof AuthenticatedSurgeryRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/visit-summaries': typeof AuthenticatedVisitSummariesRoute
  '/wristbands': typeof AuthenticatedWristbandsRoute
  '/portal': typeof PortalPortalRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/infrastructure/automation': typeof AuthenticatedInfrastructureAutomationRoute
  '/infrastructure/dashboard': typeof AuthenticatedInfrastructureDashboardRoute
  '/infrastructure/equipment': typeof AuthenticatedInfrastructureEquipmentRoute
  '/infrastructure/map': typeof AuthenticatedInfrastructureMapRoute
  '/infrastructure/settings': typeof AuthenticatedInfrastructureSettingsRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/staff/new': typeof AuthenticatedStaffNewRoute
  '/portal/ai-chat': typeof PortalPortalAiChatRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/billing': typeof PortalPortalBillingRoute
  '/portal/clinic-info': typeof PortalPortalClinicInfoRoute
  '/portal/dashboard': typeof PortalPortalDashboardRoute
  '/portal/exercise-progress': typeof PortalPortalExerciseProgressRoute
  '/portal/exercise-session': typeof PortalPortalExerciseSessionRoute
  '/portal/exercises': typeof PortalPortalExercisesRoute
  '/portal/family': typeof PortalPortalFamilyRoute
  '/portal/history': typeof PortalPortalHistoryRoute
  '/portal/loyalty': typeof PortalPortalLoyaltyRoute
  '/portal/medical-card': typeof PortalPortalMedicalCardRoute
  '/portal/messages': typeof PortalPortalMessagesRoute
  '/portal/profile': typeof PortalPortalProfileRoute
  '/portal/ratings': typeof PortalPortalRatingsRoute
  '/portal/recovery': typeof PortalPortalRecoveryRoute
  '/portal/reminders': typeof PortalPortalRemindersRoute
  '/portal/results': typeof PortalPortalResultsRoute
  '/portal/schedule': typeof PortalPortalScheduleRoute
  '/portal/treatment': typeof PortalPortalTreatmentRoute
  '/infrastructure': typeof AuthenticatedInfrastructureIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/patients/$patientId/ai': typeof AuthenticatedPatientsPatientIdAiRoute
  '/patients/$patientId/billing': typeof AuthenticatedPatientsPatientIdBillingRoute
  '/patients/$patientId/diagnoses': typeof AuthenticatedPatientsPatientIdDiagnosesRoute
  '/patients/$patientId/documents': typeof AuthenticatedPatientsPatientIdDocumentsRoute
  '/patients/$patientId/dynamics': typeof AuthenticatedPatientsPatientIdDynamicsRoute
  '/patients/$patientId/labs': typeof AuthenticatedPatientsPatientIdLabsRoute
  '/patients/$patientId/medications': typeof AuthenticatedPatientsPatientIdMedicationsRoute
  '/patients/$patientId/monitoring': typeof AuthenticatedPatientsPatientIdMonitoringRoute
  '/patients/$patientId/overview': typeof AuthenticatedPatientsPatientIdOverviewRoute
  '/patients/$patientId/procedures': typeof AuthenticatedPatientsPatientIdProceduresRoute
  '/patients/$patientId/rooms': typeof AuthenticatedPatientsPatientIdRoomsRoute
  '/patients/$patientId/stroke': typeof AuthenticatedPatientsPatientIdStrokeRoute
  '/patients/$patientId/treatment': typeof AuthenticatedPatientsPatientIdTreatmentRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdIndexRoute
  '/patients/$patientId/history/$entryId': typeof AuthenticatedPatientsPatientIdHistoryEntryIdRoute
  '/patients/$patientId/history/new': typeof AuthenticatedPatientsPatientIdHistoryNewRoute
  '/patients/$patientId/history': typeof AuthenticatedPatientsPatientIdHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/bedside': typeof BedsideRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/chief-dashboard': typeof AuthenticatedChiefDashboardRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/document-templates': typeof AuthenticatedDocumentTemplatesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/infection-control': typeof AuthenticatedInfectionControlRoute
  '/_authenticated/infrastructure': typeof AuthenticatedInfrastructureRouteWithChildren
  '/_authenticated/laboratory': typeof AuthenticatedLaboratoryRoute
  '/_authenticated/medicine-settings': typeof AuthenticatedMedicineSettingsRoute
  '/_authenticated/notification-logs': typeof AuthenticatedNotificationLogsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/nurse-diary': typeof AuthenticatedNurseDiaryRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/qr-scan': typeof AuthenticatedQrScanRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/rbac': typeof AuthenticatedRbacRoute
  '/_authenticated/rbac-user': typeof AuthenticatedRbacUserRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/schedule-calendar': typeof AuthenticatedScheduleCalendarRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/surgery': typeof AuthenticatedSurgeryRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/telemedicine': typeof AuthenticatedTelemedicineRoute
  '/_authenticated/visit-summaries': typeof AuthenticatedVisitSummariesRoute
  '/_authenticated/wristbands': typeof AuthenticatedWristbandsRoute
  '/portal/_portal': typeof PortalPortalRouteWithChildren
  '/portal/login': typeof PortalLoginRoute
  '/_authenticated/infrastructure/automation': typeof AuthenticatedInfrastructureAutomationRoute
  '/_authenticated/infrastructure/dashboard': typeof AuthenticatedInfrastructureDashboardRoute
  '/_authenticated/infrastructure/equipment': typeof AuthenticatedInfrastructureEquipmentRoute
  '/_authenticated/infrastructure/map': typeof AuthenticatedInfrastructureMapRoute
  '/_authenticated/infrastructure/settings': typeof AuthenticatedInfrastructureSettingsRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/staff/new': typeof AuthenticatedStaffNewRoute
  '/portal/_portal/ai-chat': typeof PortalPortalAiChatRoute
  '/portal/_portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/_portal/billing': typeof PortalPortalBillingRoute
  '/portal/_portal/clinic-info': typeof PortalPortalClinicInfoRoute
  '/portal/_portal/dashboard': typeof PortalPortalDashboardRoute
  '/portal/_portal/exercise-progress': typeof PortalPortalExerciseProgressRoute
  '/portal/_portal/exercise-session': typeof PortalPortalExerciseSessionRoute
  '/portal/_portal/exercises': typeof PortalPortalExercisesRoute
  '/portal/_portal/family': typeof PortalPortalFamilyRoute
  '/portal/_portal/history': typeof PortalPortalHistoryRoute
  '/portal/_portal/loyalty': typeof PortalPortalLoyaltyRoute
  '/portal/_portal/medical-card': typeof PortalPortalMedicalCardRoute
  '/portal/_portal/messages': typeof PortalPortalMessagesRoute
  '/portal/_portal/profile': typeof PortalPortalProfileRoute
  '/portal/_portal/ratings': typeof PortalPortalRatingsRoute
  '/portal/_portal/recovery': typeof PortalPortalRecoveryRoute
  '/portal/_portal/reminders': typeof PortalPortalRemindersRoute
  '/portal/_portal/results': typeof PortalPortalResultsRoute
  '/portal/_portal/schedule': typeof PortalPortalScheduleRoute
  '/portal/_portal/treatment': typeof PortalPortalTreatmentRoute
  '/_authenticated/infrastructure/': typeof AuthenticatedInfrastructureIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/patients/$patientId/ai': typeof AuthenticatedPatientsPatientIdAiRoute
  '/_authenticated/patients/$patientId/billing': typeof AuthenticatedPatientsPatientIdBillingRoute
  '/_authenticated/patients/$patientId/diagnoses': typeof AuthenticatedPatientsPatientIdDiagnosesRoute
  '/_authenticated/patients/$patientId/documents': typeof AuthenticatedPatientsPatientIdDocumentsRoute
  '/_authenticated/patients/$patientId/dynamics': typeof AuthenticatedPatientsPatientIdDynamicsRoute
  '/_authenticated/patients/$patientId/history': typeof AuthenticatedPatientsPatientIdHistoryRouteWithChildren
  '/_authenticated/patients/$patientId/labs': typeof AuthenticatedPatientsPatientIdLabsRoute
  '/_authenticated/patients/$patientId/medications': typeof AuthenticatedPatientsPatientIdMedicationsRoute
  '/_authenticated/patients/$patientId/monitoring': typeof AuthenticatedPatientsPatientIdMonitoringRoute
  '/_authenticated/patients/$patientId/overview': typeof AuthenticatedPatientsPatientIdOverviewRoute
  '/_authenticated/patients/$patientId/procedures': typeof AuthenticatedPatientsPatientIdProceduresRoute
  '/_authenticated/patients/$patientId/rooms': typeof AuthenticatedPatientsPatientIdRoomsRoute
  '/_authenticated/patients/$patientId/stroke': typeof AuthenticatedPatientsPatientIdStrokeRoute
  '/_authenticated/patients/$patientId/treatment': typeof AuthenticatedPatientsPatientIdTreatmentRoute
  '/_authenticated/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
  '/_authenticated/patients/$patientId/history/$entryId': typeof AuthenticatedPatientsPatientIdHistoryEntryIdRoute
  '/_authenticated/patients/$patientId/history/new': typeof AuthenticatedPatientsPatientIdHistoryNewRoute
  '/_authenticated/patients/$patientId/history/': typeof AuthenticatedPatientsPatientIdHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bedside'
    | '/lobby'
    | '/login'
    | '/analytics'
    | '/audit'
    | '/chat'
    | '/chief-dashboard'
    | '/dashboard'
    | '/document-templates'
    | '/finance'
    | '/infection-control'
    | '/infrastructure'
    | '/laboratory'
    | '/medicine-settings'
    | '/notification-logs'
    | '/notifications'
    | '/nurse-diary'
    | '/patients'
    | '/pharmacy'
    | '/predictions'
    | '/qr-scan'
    | '/queue'
    | '/rbac'
    | '/rbac-user'
    | '/referrals'
    | '/reports'
    | '/schedule'
    | '/schedule-calendar'
    | '/staff'
    | '/surgery'
    | '/tasks'
    | '/telemedicine'
    | '/visit-summaries'
    | '/wristbands'
    | '/portal'
    | '/portal/login'
    | '/infrastructure/automation'
    | '/infrastructure/dashboard'
    | '/infrastructure/equipment'
    | '/infrastructure/map'
    | '/infrastructure/settings'
    | '/patients/$patientId'
    | '/patients/new'
    | '/staff/$staffId'
    | '/staff/new'
    | '/portal/ai-chat'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/clinic-info'
    | '/portal/dashboard'
    | '/portal/exercise-progress'
    | '/portal/exercise-session'
    | '/portal/exercises'
    | '/portal/family'
    | '/portal/history'
    | '/portal/loyalty'
    | '/portal/medical-card'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/ratings'
    | '/portal/recovery'
    | '/portal/reminders'
    | '/portal/results'
    | '/portal/schedule'
    | '/portal/treatment'
    | '/infrastructure/'
    | '/patients/'
    | '/staff/'
    | '/patients/$patientId/ai'
    | '/patients/$patientId/billing'
    | '/patients/$patientId/diagnoses'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/dynamics'
    | '/patients/$patientId/history'
    | '/patients/$patientId/labs'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/monitoring'
    | '/patients/$patientId/overview'
    | '/patients/$patientId/procedures'
    | '/patients/$patientId/rooms'
    | '/patients/$patientId/stroke'
    | '/patients/$patientId/treatment'
    | '/patients/$patientId/'
    | '/patients/$patientId/history/$entryId'
    | '/patients/$patientId/history/new'
    | '/patients/$patientId/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bedside'
    | '/lobby'
    | '/login'
    | '/analytics'
    | '/audit'
    | '/chat'
    | '/chief-dashboard'
    | '/dashboard'
    | '/document-templates'
    | '/finance'
    | '/infection-control'
    | '/laboratory'
    | '/medicine-settings'
    | '/notification-logs'
    | '/notifications'
    | '/nurse-diary'
    | '/pharmacy'
    | '/predictions'
    | '/qr-scan'
    | '/queue'
    | '/rbac'
    | '/rbac-user'
    | '/referrals'
    | '/reports'
    | '/schedule'
    | '/schedule-calendar'
    | '/surgery'
    | '/tasks'
    | '/telemedicine'
    | '/visit-summaries'
    | '/wristbands'
    | '/portal'
    | '/portal/login'
    | '/infrastructure/automation'
    | '/infrastructure/dashboard'
    | '/infrastructure/equipment'
    | '/infrastructure/map'
    | '/infrastructure/settings'
    | '/patients/new'
    | '/staff/$staffId'
    | '/staff/new'
    | '/portal/ai-chat'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/clinic-info'
    | '/portal/dashboard'
    | '/portal/exercise-progress'
    | '/portal/exercise-session'
    | '/portal/exercises'
    | '/portal/family'
    | '/portal/history'
    | '/portal/loyalty'
    | '/portal/medical-card'
    | '/portal/messages'
    | '/portal/profile'
    | '/portal/ratings'
    | '/portal/recovery'
    | '/portal/reminders'
    | '/portal/results'
    | '/portal/schedule'
    | '/portal/treatment'
    | '/infrastructure'
    | '/patients'
    | '/staff'
    | '/patients/$patientId/ai'
    | '/patients/$patientId/billing'
    | '/patients/$patientId/diagnoses'
    | '/patients/$patientId/documents'
    | '/patients/$patientId/dynamics'
    | '/patients/$patientId/labs'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/monitoring'
    | '/patients/$patientId/overview'
    | '/patients/$patientId/procedures'
    | '/patients/$patientId/rooms'
    | '/patients/$patientId/stroke'
    | '/patients/$patientId/treatment'
    | '/patients/$patientId'
    | '/patients/$patientId/history/$entryId'
    | '/patients/$patientId/history/new'
    | '/patients/$patientId/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bedside'
    | '/lobby'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/chat'
    | '/_authenticated/chief-dashboard'
    | '/_authenticated/dashboard'
    | '/_authenticated/document-templates'
    | '/_authenticated/finance'
    | '/_authenticated/infection-control'
    | '/_authenticated/infrastructure'
    | '/_authenticated/laboratory'
    | '/_authenticated/medicine-settings'
    | '/_authenticated/notification-logs'
    | '/_authenticated/notifications'
    | '/_authenticated/nurse-diary'
    | '/_authenticated/patients'
    | '/_authenticated/pharmacy'
    | '/_authenticated/predictions'
    | '/_authenticated/qr-scan'
    | '/_authenticated/queue'
    | '/_authenticated/rbac'
    | '/_authenticated/rbac-user'
    | '/_authenticated/referrals'
    | '/_authenticated/reports'
    | '/_authenticated/schedule'
    | '/_authenticated/schedule-calendar'
    | '/_authenticated/staff'
    | '/_authenticated/surgery'
    | '/_authenticated/tasks'
    | '/_authenticated/telemedicine'
    | '/_authenticated/visit-summaries'
    | '/_authenticated/wristbands'
    | '/portal/_portal'
    | '/portal/login'
    | '/_authenticated/infrastructure/automation'
    | '/_authenticated/infrastructure/dashboard'
    | '/_authenticated/infrastructure/equipment'
    | '/_authenticated/infrastructure/map'
    | '/_authenticated/infrastructure/settings'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/new'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/staff/new'
    | '/portal/_portal/ai-chat'
    | '/portal/_portal/appointments'
    | '/portal/_portal/billing'
    | '/portal/_portal/clinic-info'
    | '/portal/_portal/dashboard'
    | '/portal/_portal/exercise-progress'
    | '/portal/_portal/exercise-session'
    | '/portal/_portal/exercises'
    | '/portal/_portal/family'
    | '/portal/_portal/history'
    | '/portal/_portal/loyalty'
    | '/portal/_portal/medical-card'
    | '/portal/_portal/messages'
    | '/portal/_portal/profile'
    | '/portal/_portal/ratings'
    | '/portal/_portal/recovery'
    | '/portal/_portal/reminders'
    | '/portal/_portal/results'
    | '/portal/_portal/schedule'
    | '/portal/_portal/treatment'
    | '/_authenticated/infrastructure/'
    | '/_authenticated/patients/'
    | '/_authenticated/staff/'
    | '/_authenticated/patients/$patientId/ai'
    | '/_authenticated/patients/$patientId/billing'
    | '/_authenticated/patients/$patientId/diagnoses'
    | '/_authenticated/patients/$patientId/documents'
    | '/_authenticated/patients/$patientId/dynamics'
    | '/_authenticated/patients/$patientId/history'
    | '/_authenticated/patients/$patientId/labs'
    | '/_authenticated/patients/$patientId/medications'
    | '/_authenticated/patients/$patientId/monitoring'
    | '/_authenticated/patients/$patientId/overview'
    | '/_authenticated/patients/$patientId/procedures'
    | '/_authenticated/patients/$patientId/rooms'
    | '/_authenticated/patients/$patientId/stroke'
    | '/_authenticated/patients/$patientId/treatment'
    | '/_authenticated/patients/$patientId/'
    | '/_authenticated/patients/$patientId/history/$entryId'
    | '/_authenticated/patients/$patientId/history/new'
    | '/_authenticated/patients/$patientId/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BedsideRoute: typeof BedsideRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  PortalPortalRoute: typeof PortalPortalRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedside': {
      id: '/bedside'
      path: '/bedside'
      fullPath: '/bedside'
      preLoaderRoute: typeof BedsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/_portal': {
      id: '/portal/_portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wristbands': {
      id: '/_authenticated/wristbands'
      path: '/wristbands'
      fullPath: '/wristbands'
      preLoaderRoute: typeof AuthenticatedWristbandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visit-summaries': {
      id: '/_authenticated/visit-summaries'
      path: '/visit-summaries'
      fullPath: '/visit-summaries'
      preLoaderRoute: typeof AuthenticatedVisitSummariesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telemedicine': {
      id: '/_authenticated/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof AuthenticatedTelemedicineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/surgery': {
      id: '/_authenticated/surgery'
      path: '/surgery'
      fullPath: '/surgery'
      preLoaderRoute: typeof AuthenticatedSurgeryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule-calendar': {
      id: '/_authenticated/schedule-calendar'
      path: '/schedule-calendar'
      fullPath: '/schedule-calendar'
      preLoaderRoute: typeof AuthenticatedScheduleCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rbac-user': {
      id: '/_authenticated/rbac-user'
      path: '/rbac-user'
      fullPath: '/rbac-user'
      preLoaderRoute: typeof AuthenticatedRbacUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rbac': {
      id: '/_authenticated/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AuthenticatedRbacRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr-scan': {
      id: '/_authenticated/qr-scan'
      path: '/qr-scan'
      fullPath: '/qr-scan'
      preLoaderRoute: typeof AuthenticatedQrScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nurse-diary': {
      id: '/_authenticated/nurse-diary'
      path: '/nurse-diary'
      fullPath: '/nurse-diary'
      preLoaderRoute: typeof AuthenticatedNurseDiaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notification-logs': {
      id: '/_authenticated/notification-logs'
      path: '/notification-logs'
      fullPath: '/notification-logs'
      preLoaderRoute: typeof AuthenticatedNotificationLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medicine-settings': {
      id: '/_authenticated/medicine-settings'
      path: '/medicine-settings'
      fullPath: '/medicine-settings'
      preLoaderRoute: typeof AuthenticatedMedicineSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laboratory': {
      id: '/_authenticated/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof AuthenticatedLaboratoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/infrastructure': {
      id: '/_authenticated/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof AuthenticatedInfrastructureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/infection-control': {
      id: '/_authenticated/infection-control'
      path: '/infection-control'
      fullPath: '/infection-control'
      preLoaderRoute: typeof AuthenticatedInfectionControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/document-templates': {
      id: '/_authenticated/document-templates'
      path: '/document-templates'
      fullPath: '/document-templates'
      preLoaderRoute: typeof AuthenticatedDocumentTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chief-dashboard': {
      id: '/_authenticated/chief-dashboard'
      path: '/chief-dashboard'
      fullPath: '/chief-dashboard'
      preLoaderRoute: typeof AuthenticatedChiefDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/infrastructure/': {
      id: '/_authenticated/infrastructure/'
      path: '/'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof AuthenticatedInfrastructureIndexRouteImport
      parentRoute: typeof AuthenticatedInfrastructureRoute
    }
    '/portal/_portal/treatment': {
      id: '/portal/_portal/treatment'
      path: '/treatment'
      fullPath: '/portal/treatment'
      preLoaderRoute: typeof PortalPortalTreatmentRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/schedule': {
      id: '/portal/_portal/schedule'
      path: '/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof PortalPortalScheduleRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/results': {
      id: '/portal/_portal/results'
      path: '/results'
      fullPath: '/portal/results'
      preLoaderRoute: typeof PortalPortalResultsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/reminders': {
      id: '/portal/_portal/reminders'
      path: '/reminders'
      fullPath: '/portal/reminders'
      preLoaderRoute: typeof PortalPortalRemindersRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/recovery': {
      id: '/portal/_portal/recovery'
      path: '/recovery'
      fullPath: '/portal/recovery'
      preLoaderRoute: typeof PortalPortalRecoveryRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/ratings': {
      id: '/portal/_portal/ratings'
      path: '/ratings'
      fullPath: '/portal/ratings'
      preLoaderRoute: typeof PortalPortalRatingsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/profile': {
      id: '/portal/_portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalPortalProfileRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/messages': {
      id: '/portal/_portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalPortalMessagesRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/medical-card': {
      id: '/portal/_portal/medical-card'
      path: '/medical-card'
      fullPath: '/portal/medical-card'
      preLoaderRoute: typeof PortalPortalMedicalCardRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/loyalty': {
      id: '/portal/_portal/loyalty'
      path: '/loyalty'
      fullPath: '/portal/loyalty'
      preLoaderRoute: typeof PortalPortalLoyaltyRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/history': {
      id: '/portal/_portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof PortalPortalHistoryRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/family': {
      id: '/portal/_portal/family'
      path: '/family'
      fullPath: '/portal/family'
      preLoaderRoute: typeof PortalPortalFamilyRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/exercises': {
      id: '/portal/_portal/exercises'
      path: '/exercises'
      fullPath: '/portal/exercises'
      preLoaderRoute: typeof PortalPortalExercisesRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/exercise-session': {
      id: '/portal/_portal/exercise-session'
      path: '/exercise-session'
      fullPath: '/portal/exercise-session'
      preLoaderRoute: typeof PortalPortalExerciseSessionRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/exercise-progress': {
      id: '/portal/_portal/exercise-progress'
      path: '/exercise-progress'
      fullPath: '/portal/exercise-progress'
      preLoaderRoute: typeof PortalPortalExerciseProgressRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/dashboard': {
      id: '/portal/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalPortalDashboardRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/clinic-info': {
      id: '/portal/_portal/clinic-info'
      path: '/clinic-info'
      fullPath: '/portal/clinic-info'
      preLoaderRoute: typeof PortalPortalClinicInfoRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/billing': {
      id: '/portal/_portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalPortalBillingRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/appointments': {
      id: '/portal/_portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalPortalAppointmentsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/ai-chat': {
      id: '/portal/_portal/ai-chat'
      path: '/ai-chat'
      fullPath: '/portal/ai-chat'
      preLoaderRoute: typeof PortalPortalAiChatRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/_authenticated/staff/new': {
      id: '/_authenticated/staff/new'
      path: '/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AuthenticatedStaffNewRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/infrastructure/settings': {
      id: '/_authenticated/infrastructure/settings'
      path: '/settings'
      fullPath: '/infrastructure/settings'
      preLoaderRoute: typeof AuthenticatedInfrastructureSettingsRouteImport
      parentRoute: typeof AuthenticatedInfrastructureRoute
    }
    '/_authenticated/infrastructure/map': {
      id: '/_authenticated/infrastructure/map'
      path: '/map'
      fullPath: '/infrastructure/map'
      preLoaderRoute: typeof AuthenticatedInfrastructureMapRouteImport
      parentRoute: typeof AuthenticatedInfrastructureRoute
    }
    '/_authenticated/infrastructure/equipment': {
      id: '/_authenticated/infrastructure/equipment'
      path: '/equipment'
      fullPath: '/infrastructure/equipment'
      preLoaderRoute: typeof AuthenticatedInfrastructureEquipmentRouteImport
      parentRoute: typeof AuthenticatedInfrastructureRoute
    }
    '/_authenticated/infrastructure/dashboard': {
      id: '/_authenticated/infrastructure/dashboard'
      path: '/dashboard'
      fullPath: '/infrastructure/dashboard'
      preLoaderRoute: typeof AuthenticatedInfrastructureDashboardRouteImport
      parentRoute: typeof AuthenticatedInfrastructureRoute
    }
    '/_authenticated/infrastructure/automation': {
      id: '/_authenticated/infrastructure/automation'
      path: '/automation'
      fullPath: '/infrastructure/automation'
      preLoaderRoute: typeof AuthenticatedInfrastructureAutomationRouteImport
      parentRoute: typeof AuthenticatedInfrastructureRoute
    }
    '/_authenticated/patients/$patientId/': {
      id: '/_authenticated/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/treatment': {
      id: '/_authenticated/patients/$patientId/treatment'
      path: '/treatment'
      fullPath: '/patients/$patientId/treatment'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdTreatmentRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/stroke': {
      id: '/_authenticated/patients/$patientId/stroke'
      path: '/stroke'
      fullPath: '/patients/$patientId/stroke'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdStrokeRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/rooms': {
      id: '/_authenticated/patients/$patientId/rooms'
      path: '/rooms'
      fullPath: '/patients/$patientId/rooms'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRoomsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/procedures': {
      id: '/_authenticated/patients/$patientId/procedures'
      path: '/procedures'
      fullPath: '/patients/$patientId/procedures'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdProceduresRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/overview': {
      id: '/_authenticated/patients/$patientId/overview'
      path: '/overview'
      fullPath: '/patients/$patientId/overview'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdOverviewRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/monitoring': {
      id: '/_authenticated/patients/$patientId/monitoring'
      path: '/monitoring'
      fullPath: '/patients/$patientId/monitoring'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdMonitoringRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/medications': {
      id: '/_authenticated/patients/$patientId/medications'
      path: '/medications'
      fullPath: '/patients/$patientId/medications'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdMedicationsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/labs': {
      id: '/_authenticated/patients/$patientId/labs'
      path: '/labs'
      fullPath: '/patients/$patientId/labs'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdLabsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/history': {
      id: '/_authenticated/patients/$patientId/history'
      path: '/history'
      fullPath: '/patients/$patientId/history'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdHistoryRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/dynamics': {
      id: '/_authenticated/patients/$patientId/dynamics'
      path: '/dynamics'
      fullPath: '/patients/$patientId/dynamics'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdDynamicsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/documents': {
      id: '/_authenticated/patients/$patientId/documents'
      path: '/documents'
      fullPath: '/patients/$patientId/documents'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/diagnoses': {
      id: '/_authenticated/patients/$patientId/diagnoses'
      path: '/diagnoses'
      fullPath: '/patients/$patientId/diagnoses'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdDiagnosesRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/billing': {
      id: '/_authenticated/patients/$patientId/billing'
      path: '/billing'
      fullPath: '/patients/$patientId/billing'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdBillingRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/ai': {
      id: '/_authenticated/patients/$patientId/ai'
      path: '/ai'
      fullPath: '/patients/$patientId/ai'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdAiRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/history/': {
      id: '/_authenticated/patients/$patientId/history/'
      path: '/'
      fullPath: '/patients/$patientId/history/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdHistoryRoute
    }
    '/_authenticated/patients/$patientId/history/new': {
      id: '/_authenticated/patients/$patientId/history/new'
      path: '/new'
      fullPath: '/patients/$patientId/history/new'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdHistoryNewRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdHistoryRoute
    }
    '/_authenticated/patients/$patientId/history/$entryId': {
      id: '/_authenticated/patients/$patientId/history/$entryId'
      path: '/$entryId'
      fullPath: '/patients/$patientId/history/$entryId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdHistoryEntryIdRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdHistoryRoute
    }
  }
}

interface AuthenticatedInfrastructureRouteChildren {
  AuthenticatedInfrastructureAutomationRoute: typeof AuthenticatedInfrastructureAutomationRoute
  AuthenticatedInfrastructureDashboardRoute: typeof AuthenticatedInfrastructureDashboardRoute
  AuthenticatedInfrastructureEquipmentRoute: typeof AuthenticatedInfrastructureEquipmentRoute
  AuthenticatedInfrastructureMapRoute: typeof AuthenticatedInfrastructureMapRoute
  AuthenticatedInfrastructureSettingsRoute: typeof AuthenticatedInfrastructureSettingsRoute
  AuthenticatedInfrastructureIndexRoute: typeof AuthenticatedInfrastructureIndexRoute
}

const AuthenticatedInfrastructureRouteChildren: AuthenticatedInfrastructureRouteChildren =
  {
    AuthenticatedInfrastructureAutomationRoute:
      AuthenticatedInfrastructureAutomationRoute,
    AuthenticatedInfrastructureDashboardRoute:
      AuthenticatedInfrastructureDashboardRoute,
    AuthenticatedInfrastructureEquipmentRoute:
      AuthenticatedInfrastructureEquipmentRoute,
    AuthenticatedInfrastructureMapRoute: AuthenticatedInfrastructureMapRoute,
    AuthenticatedInfrastructureSettingsRoute:
      AuthenticatedInfrastructureSettingsRoute,
    AuthenticatedInfrastructureIndexRoute:
      AuthenticatedInfrastructureIndexRoute,
  }

const AuthenticatedInfrastructureRouteWithChildren =
  AuthenticatedInfrastructureRoute._addFileChildren(
    AuthenticatedInfrastructureRouteChildren,
  )

interface AuthenticatedPatientsPatientIdHistoryRouteChildren {
  AuthenticatedPatientsPatientIdHistoryEntryIdRoute: typeof AuthenticatedPatientsPatientIdHistoryEntryIdRoute
  AuthenticatedPatientsPatientIdHistoryNewRoute: typeof AuthenticatedPatientsPatientIdHistoryNewRoute
  AuthenticatedPatientsPatientIdHistoryIndexRoute: typeof AuthenticatedPatientsPatientIdHistoryIndexRoute
}

const AuthenticatedPatientsPatientIdHistoryRouteChildren: AuthenticatedPatientsPatientIdHistoryRouteChildren =
  {
    AuthenticatedPatientsPatientIdHistoryEntryIdRoute:
      AuthenticatedPatientsPatientIdHistoryEntryIdRoute,
    AuthenticatedPatientsPatientIdHistoryNewRoute:
      AuthenticatedPatientsPatientIdHistoryNewRoute,
    AuthenticatedPatientsPatientIdHistoryIndexRoute:
      AuthenticatedPatientsPatientIdHistoryIndexRoute,
  }

const AuthenticatedPatientsPatientIdHistoryRouteWithChildren =
  AuthenticatedPatientsPatientIdHistoryRoute._addFileChildren(
    AuthenticatedPatientsPatientIdHistoryRouteChildren,
  )

interface AuthenticatedPatientsPatientIdRouteChildren {
  AuthenticatedPatientsPatientIdAiRoute: typeof AuthenticatedPatientsPatientIdAiRoute
  AuthenticatedPatientsPatientIdBillingRoute: typeof AuthenticatedPatientsPatientIdBillingRoute
  AuthenticatedPatientsPatientIdDiagnosesRoute: typeof AuthenticatedPatientsPatientIdDiagnosesRoute
  AuthenticatedPatientsPatientIdDocumentsRoute: typeof AuthenticatedPatientsPatientIdDocumentsRoute
  AuthenticatedPatientsPatientIdDynamicsRoute: typeof AuthenticatedPatientsPatientIdDynamicsRoute
  AuthenticatedPatientsPatientIdHistoryRoute: typeof AuthenticatedPatientsPatientIdHistoryRouteWithChildren
  AuthenticatedPatientsPatientIdLabsRoute: typeof AuthenticatedPatientsPatientIdLabsRoute
  AuthenticatedPatientsPatientIdMedicationsRoute: typeof AuthenticatedPatientsPatientIdMedicationsRoute
  AuthenticatedPatientsPatientIdMonitoringRoute: typeof AuthenticatedPatientsPatientIdMonitoringRoute
  AuthenticatedPatientsPatientIdOverviewRoute: typeof AuthenticatedPatientsPatientIdOverviewRoute
  AuthenticatedPatientsPatientIdProceduresRoute: typeof AuthenticatedPatientsPatientIdProceduresRoute
  AuthenticatedPatientsPatientIdRoomsRoute: typeof AuthenticatedPatientsPatientIdRoomsRoute
  AuthenticatedPatientsPatientIdStrokeRoute: typeof AuthenticatedPatientsPatientIdStrokeRoute
  AuthenticatedPatientsPatientIdTreatmentRoute: typeof AuthenticatedPatientsPatientIdTreatmentRoute
  AuthenticatedPatientsPatientIdIndexRoute: typeof AuthenticatedPatientsPatientIdIndexRoute
}

const AuthenticatedPatientsPatientIdRouteChildren: AuthenticatedPatientsPatientIdRouteChildren =
  {
    AuthenticatedPatientsPatientIdAiRoute:
      AuthenticatedPatientsPatientIdAiRoute,
    AuthenticatedPatientsPatientIdBillingRoute:
      AuthenticatedPatientsPatientIdBillingRoute,
    AuthenticatedPatientsPatientIdDiagnosesRoute:
      AuthenticatedPatientsPatientIdDiagnosesRoute,
    AuthenticatedPatientsPatientIdDocumentsRoute:
      AuthenticatedPatientsPatientIdDocumentsRoute,
    AuthenticatedPatientsPatientIdDynamicsRoute:
      AuthenticatedPatientsPatientIdDynamicsRoute,
    AuthenticatedPatientsPatientIdHistoryRoute:
      AuthenticatedPatientsPatientIdHistoryRouteWithChildren,
    AuthenticatedPatientsPatientIdLabsRoute:
      AuthenticatedPatientsPatientIdLabsRoute,
    AuthenticatedPatientsPatientIdMedicationsRoute:
      AuthenticatedPatientsPatientIdMedicationsRoute,
    AuthenticatedPatientsPatientIdMonitoringRoute:
      AuthenticatedPatientsPatientIdMonitoringRoute,
    AuthenticatedPatientsPatientIdOverviewRoute:
      AuthenticatedPatientsPatientIdOverviewRoute,
    AuthenticatedPatientsPatientIdProceduresRoute:
      AuthenticatedPatientsPatientIdProceduresRoute,
    AuthenticatedPatientsPatientIdRoomsRoute:
      AuthenticatedPatientsPatientIdRoomsRoute,
    AuthenticatedPatientsPatientIdStrokeRoute:
      AuthenticatedPatientsPatientIdStrokeRoute,
    AuthenticatedPatientsPatientIdTreatmentRoute:
      AuthenticatedPatientsPatientIdTreatmentRoute,
    AuthenticatedPatientsPatientIdIndexRoute:
      AuthenticatedPatientsPatientIdIndexRoute,
  }

const AuthenticatedPatientsPatientIdRouteWithChildren =
  AuthenticatedPatientsPatientIdRoute._addFileChildren(
    AuthenticatedPatientsPatientIdRouteChildren,
  )

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRouteWithChildren
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute:
    AuthenticatedPatientsPatientIdRouteWithChildren,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
  AuthenticatedStaffNewRoute: typeof AuthenticatedStaffNewRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
  AuthenticatedStaffNewRoute: AuthenticatedStaffNewRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedChiefDashboardRoute: typeof AuthenticatedChiefDashboardRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentTemplatesRoute: typeof AuthenticatedDocumentTemplatesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInfectionControlRoute: typeof AuthenticatedInfectionControlRoute
  AuthenticatedInfrastructureRoute: typeof AuthenticatedInfrastructureRouteWithChildren
  AuthenticatedLaboratoryRoute: typeof AuthenticatedLaboratoryRoute
  AuthenticatedMedicineSettingsRoute: typeof AuthenticatedMedicineSettingsRoute
  AuthenticatedNotificationLogsRoute: typeof AuthenticatedNotificationLogsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedNurseDiaryRoute: typeof AuthenticatedNurseDiaryRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedQrScanRoute: typeof AuthenticatedQrScanRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedRbacRoute: typeof AuthenticatedRbacRoute
  AuthenticatedRbacUserRoute: typeof AuthenticatedRbacUserRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedScheduleCalendarRoute: typeof AuthenticatedScheduleCalendarRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedSurgeryRoute: typeof AuthenticatedSurgeryRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTelemedicineRoute: typeof AuthenticatedTelemedicineRoute
  AuthenticatedVisitSummariesRoute: typeof AuthenticatedVisitSummariesRoute
  AuthenticatedWristbandsRoute: typeof AuthenticatedWristbandsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedChiefDashboardRoute: AuthenticatedChiefDashboardRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentTemplatesRoute: AuthenticatedDocumentTemplatesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInfectionControlRoute: AuthenticatedInfectionControlRoute,
  AuthenticatedInfrastructureRoute:
    AuthenticatedInfrastructureRouteWithChildren,
  AuthenticatedLaboratoryRoute: AuthenticatedLaboratoryRoute,
  AuthenticatedMedicineSettingsRoute: AuthenticatedMedicineSettingsRoute,
  AuthenticatedNotificationLogsRoute: AuthenticatedNotificationLogsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedNurseDiaryRoute: AuthenticatedNurseDiaryRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedQrScanRoute: AuthenticatedQrScanRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedRbacRoute: AuthenticatedRbacRoute,
  AuthenticatedRbacUserRoute: AuthenticatedRbacUserRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedScheduleCalendarRoute: AuthenticatedScheduleCalendarRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedSurgeryRoute: AuthenticatedSurgeryRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTelemedicineRoute: AuthenticatedTelemedicineRoute,
  AuthenticatedVisitSummariesRoute: AuthenticatedVisitSummariesRoute,
  AuthenticatedWristbandsRoute: AuthenticatedWristbandsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalPortalRouteChildren {
  PortalPortalAiChatRoute: typeof PortalPortalAiChatRoute
  PortalPortalAppointmentsRoute: typeof PortalPortalAppointmentsRoute
  PortalPortalBillingRoute: typeof PortalPortalBillingRoute
  PortalPortalClinicInfoRoute: typeof PortalPortalClinicInfoRoute
  PortalPortalDashboardRoute: typeof PortalPortalDashboardRoute
  PortalPortalExerciseProgressRoute: typeof PortalPortalExerciseProgressRoute
  PortalPortalExerciseSessionRoute: typeof PortalPortalExerciseSessionRoute
  PortalPortalExercisesRoute: typeof PortalPortalExercisesRoute
  PortalPortalFamilyRoute: typeof PortalPortalFamilyRoute
  PortalPortalHistoryRoute: typeof PortalPortalHistoryRoute
  PortalPortalLoyaltyRoute: typeof PortalPortalLoyaltyRoute
  PortalPortalMedicalCardRoute: typeof PortalPortalMedicalCardRoute
  PortalPortalMessagesRoute: typeof PortalPortalMessagesRoute
  PortalPortalProfileRoute: typeof PortalPortalProfileRoute
  PortalPortalRatingsRoute: typeof PortalPortalRatingsRoute
  PortalPortalRecoveryRoute: typeof PortalPortalRecoveryRoute
  PortalPortalRemindersRoute: typeof PortalPortalRemindersRoute
  PortalPortalResultsRoute: typeof PortalPortalResultsRoute
  PortalPortalScheduleRoute: typeof PortalPortalScheduleRoute
  PortalPortalTreatmentRoute: typeof PortalPortalTreatmentRoute
}

const PortalPortalRouteChildren: PortalPortalRouteChildren = {
  PortalPortalAiChatRoute: PortalPortalAiChatRoute,
  PortalPortalAppointmentsRoute: PortalPortalAppointmentsRoute,
  PortalPortalBillingRoute: PortalPortalBillingRoute,
  PortalPortalClinicInfoRoute: PortalPortalClinicInfoRoute,
  PortalPortalDashboardRoute: PortalPortalDashboardRoute,
  PortalPortalExerciseProgressRoute: PortalPortalExerciseProgressRoute,
  PortalPortalExerciseSessionRoute: PortalPortalExerciseSessionRoute,
  PortalPortalExercisesRoute: PortalPortalExercisesRoute,
  PortalPortalFamilyRoute: PortalPortalFamilyRoute,
  PortalPortalHistoryRoute: PortalPortalHistoryRoute,
  PortalPortalLoyaltyRoute: PortalPortalLoyaltyRoute,
  PortalPortalMedicalCardRoute: PortalPortalMedicalCardRoute,
  PortalPortalMessagesRoute: PortalPortalMessagesRoute,
  PortalPortalProfileRoute: PortalPortalProfileRoute,
  PortalPortalRatingsRoute: PortalPortalRatingsRoute,
  PortalPortalRecoveryRoute: PortalPortalRecoveryRoute,
  PortalPortalRemindersRoute: PortalPortalRemindersRoute,
  PortalPortalResultsRoute: PortalPortalResultsRoute,
  PortalPortalScheduleRoute: PortalPortalScheduleRoute,
  PortalPortalTreatmentRoute: PortalPortalTreatmentRoute,
}

const PortalPortalRouteWithChildren = PortalPortalRoute._addFileChildren(
  PortalPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BedsideRoute: BedsideRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  PortalPortalRoute: PortalPortalRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
